#!/bin/bash
# test.script - Unit Tests for Cash Register
#
# Farhan Muhammad
# 06/07/2018

make build

# Uninitialized

echo './assn4 purchase 38 = 0 0 0 2'
./assn4 purchase 38 = 0 0 0 2		# purchase $38 with 2 $20's
echo -e "$?\n"				# expected output: 4

echo './assn4.py change 0 1 = 5'
./assn4 change 0 1 = 5			# change a $5 for 5 $1's
echo -e "$?\n"				# expected output: 4

echo './assn4 report'
./assn4 report				# report contents of current till
echo -e "$?\n"                          # expected output: 4

# Init

echo './assn4 init 15 = 10 1'
./assn4 init 15 = 10 1			# initialize the till with $15 - 10 $1's and 1 $5
echo -e "$?\n"                          # expected output: 1

echo './assn4 init 15 = 10 1 0 foo'
./assn4 init 15 = 10 1 0 foo		# initialize the till with $15 - 10 $1's, 1 $5 and a non-numeric input
echo -e "$?\n"                          # expected output: 1

echo './assn4 init 15 = 10 0 0 0'
./assn4 init 15 = 10 0 0 0		# initialize the till with $15 - only 10 $1's
echo -e "$?\n"                          # expected output: 2

echo './assn4 init 15 = 10 1 0 0'
./assn4 init 15 = 10 1 0 0		# initialize the till with $15 - 10 $1's and 1 $5
echo -e "$?\n"                          # expected output: 0

# Purchase

echo './assn4 purchase 38 = 0 2'
./assn4 purchase 38 = 0 2		# purchase $38 with 2 $20's
echo -e "$?\n"                          # expected output: 1

echo './assn4 purchase 38 = 0 0 2 0'
./assn4 purchase 38 = 0 0 2 0		# purchase $38 with 2 $10's
echo -e "$?\n"                          # expected output: 2

echo './assn4 purchase 38 = 0 0 bar 2'
./assn4 purchase 38 = 0 0 bar 2		# purchase $38 with 2 $20's and a non-numeric input
echo -e "$?\n"                          # expected output: 1

echo './assn4 purchase 38 = 0 0 0 2'
./assn4 purchase 38 = 0 0 0 2		# purchase $38 with 2 $20's
echo -e "$?\n"                          # expected output: 0... 2 0 0 0

echo './assn4 purchase 25 = 0 0 0 2'
./assn4 purchase 25 = 0 0 0 2		# purchase $25 with 2 $20's (insufficient bills)
echo -e "$?\n"                          # expected output: 3

# Change

echo './assn4 change 0 1 baz = 5'
./assn4 change 0 1 baz = 5		# change a $5 for 5 $1's with a non-numeric input
echo -e "$?\n"                          # expected output: 1

echo './assn4 change 0 1 0 = 4 0 0'
./assn4 change 0 1 0 = 4 0 0		# change a $5 for 4 $1's
echo -e "$?\n"                          # expected output: 2

echo './assn4 change 0 1 = 5'
./assn4 change 0 1 = 5			# change a $5 for 5 $1's
echo -e "$?\n"                          # expected output: 0... 5 0 0 0

echo './assn4 change 0 0 0 1 = 5 1 1 0'
./assn4 change 0 0 0 1 = 5 1 1 0	# change a $20 for 5 $1's, a $5, and a $10 (insufficient bills)
echo -e "$?\n"                          # expected output: 3

# Report

echo './assn4 report'
./assn4 report				# report contents of current till
echo -e "$?\n"                          # expected output: 0... 38 : 53 = 3 2 0 2

make clean
make build
